spring.application.name=Notification-Service
server.port=8086

# Database connection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/notificationservice_db
spring.datasource.username=root
spring.datasource.password=root123456789

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Mail configuration (using Gmail SMTP as example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sohel17sheikh@gmail.com
spring.mail.password=KGN786
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true